
package Forms;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;
import sun.security.krb5.Config;
import sun.security.krb5.KrbException;

/**
 *
 * @author androide17
 */

public class CreacionCatalogoPlantas2 extends javax.swing.JFrame {
public String nombreFile="";
public String path;
public File archivo;
        
    /**
     * Creates new form CreacionCatalogoPlantas2
     */
    public CreacionCatalogoPlantas2() {
              
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        btnSubirImagen = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtAtaque = new javax.swing.JTextField();
        txtDefenza = new javax.swing.JTextField();
        cmbModo = new javax.swing.JComboBox();
        btnGuardarPlanta = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Ingreso de Datos para el Catalogo");

        lblImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblImagen.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnSubirImagen.setText("Cargar Imagen");
        btnSubirImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirImagenActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre:");

        jLabel3.setText("Puntos de ataque:");

        jLabel4.setText("Puntos de defenza:");

        jLabel5.setText("Modo:");

        cmbModo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Disparo", "Ataque" }));

        btnGuardarPlanta.setText("Agregar Planta");
        btnGuardarPlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPlantaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Plantas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnSubirImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombre))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cmbModo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDefenza, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 7, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardarPlanta)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtAtaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtDefenza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmbModo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSubirImagen)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnGuardarPlanta, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubirImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirImagenActionPerformed

    try {
        abrir();
    } catch (IOException | InterruptedException ex) {
        Logger.getLogger(CreacionCatalogoPlantas2.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    SwingUtilities.updateComponentTreeUI(this);//ACTUALIZAMOS DATOS DE NUESTRO FORMULARIO
    
        this.txtNombre.setText(nombreFile);
        btnSubirImagen.setVisible(false);

                //System.out.println("Path archivo: ver "+archivo.getAbsolutePath().toString());
                ImageIcon tmpIconAux = new ImageIcon(getClass().getResource("/Others/"+nombreFile));
                ImageIcon tmpIcon = new ImageIcon(tmpIconAux.getImage().getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(), Image.SCALE_DEFAULT));
                lblImagen.setIcon(tmpIcon);
        
    }//GEN-LAST:event_btnSubirImagenActionPerformed

    
public void abrir() throws IOException, InterruptedException {
JFileChooser selector = new JFileChooser();//Instanciamos un objeto de la clase JFileChooser
selector.addChoosableFileFilter(new FileNameExtensionFilter("All Files", "jpg","png"));//Filtro que nos muestra archivos con extension .game

int open = selector.showDialog(null, "Abrir");
    
    if (open == JFileChooser.APPROVE_OPTION) {
    FileReader lector = null;
    BufferedReader lectorAyudante = null;

        try {

            archivo = selector.getSelectedFile();

            String PATH = selector.getSelectedFile().getAbsolutePath();//En caso de abrir un archivo que no sea de la misma extencion no se podra abrir
            String path=PATH;
            nombreFile=selector.getSelectedFile().getName();
            
        if(PATH.endsWith(".jpg")||PATH.endsWith(".png")){

       // System.out.println("Path: "+PATH);
        //System.out.println("Name: "+selector.getSelectedFile().getName());
        
            }else{
                JOptionPane.showMessageDialog(this, "No se reconoce el archivo","ERROR de extencion del archivo", JOptionPane.ERROR_MESSAGE);
                abrir();
            }

        } catch (FileNotFoundException ex) {
            ex.printStackTrace();
        } finally {
            try {
                if(null!= lector){
                    lector.close();
                }
            } catch (IOException ex) {
            ex.printStackTrace();
            }
        }
    }
}

   
    
    private void btnGuardarPlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPlantaActionPerformed
              
        int indexSelected=cmbModo.getSelectedIndex();
        char tipo;
        if (indexSelected==0) {//Disparo
           tipo='D';
        }else{
            tipo='A';
        }
        
        CreacionCatalogoPlantas.modeloLista.addElement(txtNombre.getText()+" Ataque: "+txtAtaque.getText()+" Defenza: "+txtDefenza.getText()+" Modo" +tipo);
        CreacionCatalogoPlantas.jListTipoDePlantas.setModel(CreacionCatalogoPlantas.modeloLista);
        
        Clases.Plant planta=new Clases.Plant("/Others/"+nombreFile, txtNombre.getText(), Integer.valueOf(txtAtaque.getText()), Integer.valueOf(txtDefenza.getText()), tipo);
        //System.out.println("Se creo nueva planta: "+planta.getNamePlant()+"  "+planta.getPointsOfAtack()+"  "+planta.getPointsOfDefense()+"  "+planta.getMode());
        
        
        Listas.Nodo nodoAux=new Listas.Nodo(planta);
        MainForm.listaCatalogoPlntasMAIN.add(nodoAux);
        //System.out.println("Se a;adio la planta a la listaCatalogoPlantas tamano: "+MainForm.listaCatalogoPlntasMAIN.getLengthList());
        
        dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarPlantaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreacionCatalogoPlantas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreacionCatalogoPlantas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreacionCatalogoPlantas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreacionCatalogoPlantas2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreacionCatalogoPlantas2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarPlanta;
    private javax.swing.JButton btnSubirImagen;
    private javax.swing.JComboBox cmbModo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JTextField txtAtaque;
    private javax.swing.JTextField txtDefenza;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
